"""Add is_featured to Project model

Revision ID: 6fed04920036
Revises: 95b7e42dfec1
Create Date: 2024-07-27 00:33:04.444221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fed04920036'
down_revision = '95b7e42dfec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.execute("UPDATE project SET is_featured = FALSE")
    op.alter_column('project', 'is_featured', nullable=False, server_default=sa.false())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
