"""Add is_current to Skill model

Revision ID: e8a2966c7fe7
Revises: <auto_generated_id>
Create Date: 2024-07-27 02:26:13.274966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a2966c7fe7'
down_revision = '<auto_generated_id>'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_current', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_column('is_current')

    # ### end Alembic commands ###
