"""Set default value for is_featured and make it non-nullable

Revision ID: f091092479b9
Revises: 6fed04920036
Create Date: 2024-07-27 00:40:04.003543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f091092479b9'
down_revision = '6fed04920036'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("UPDATE project SET is_featured = FALSE WHERE is_featured IS NULL")
    op.alter_column('project', 'is_featured',
                    existing_type=sa.Boolean(),
                    nullable=False,
                    server_default=sa.false())


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
